### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jam0cam** [HyphenateInc/Hyphenate-EaseUI-Android#13]
The error happens on this line, when trying to init  `EMClient.getInstance().init(context, options);`

 FATAL EXCEPTION: main Process: com.jiacorp.androidexample2, PID: 2358
 java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlite.so" not found
     at java.lang.Runtime.loadLibrary0(Runtime.java:977)
     at java.lang.System.loadLibrary(System.java:1530)
     at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source)
     at com.hyphenate.chat.EMClient.getInstance(Unknown Source)

**Comment by jerrywu12** [comment]
there’s no need to compile the EaseUI. just put it at the same directory as your demo project. Rebuild the project, then it should works.

**Comment by jam0cam** [comment]
I wasn't trying to compile the EaseUI. I included it in my own project, ran it, and got a run time exception.

**Comment by jam0cam** [comment]
Looks like the issue is caused by me setting the compileSdkVersion and targetSdkVersion to 24. Perhaps this doesn't support the latest version.

**Comment by jerrywu12** [comment]
let me sync with engineering team and get back to you ASAP. However, in the meantime, are you able to run the demo app without using the latest version 24?
Run the Android demo app from master branch https://github.com/HyphenateInc/Hyphenate-Demo-Android and EaseUI from master branch https://github.com/HyphenateInc/Hyphenate-EaseUI-Android under the same directory. 
Please feel free to leave a message if you still encounter issue.
